version: '3.4'

services:
  msauth.api:
    image: ${DOCKER_REGISTRY-}msauthapi
    build:
      context: .
      dockerfile: MSAuth/Dockerfile
    ports:
        - "32772:8080"
        - "32773:8081"

  msgym.api:
    image: ${DOCKER_REGISTRY-}msgymapi
    build:
      context: .
      dockerfile: Gym/MSGym.API/Dockerfile
    ports:
        - "32774:8080"
        - "32775:8081"


  msgamification.api:
    image: ${DOCKER_REGISTRY-}msgamificationapi
    build:
      context: .
      dockerfile: Gym/MSGamification.API/Dockerfile
    ports:
        - "32776:8080"
        - "32777:8081"




