version: '3.4'

services:
  msauth.api:
    image: ${DOCKER_REGISTRY-}msauthapi
    container_name: msauth.api
    build:
      context: .
      dockerfile: MSAuth/MSAuth.API/Dockerfile
    environment:
     - RabbitMQ__Host=amqp://auth-queue:5672
     - RabbitMQ__Username=guest
     - RabbitMQ__Password=guest
    ports:
        - 32772:8080
        - 32773:8081
    networks:
        - proxybackend

  msgym.api:
    image: ${DOCKER_REGISTRY-}msgymapi
    container_name: msgym.api
    build:
      context: .
      dockerfile: Gym/MSGym/MSGym.API/Dockerfile
    environment:
     - RabbitMQ__Host=amqp://auth-queue:5672
     - RabbitMQ__Username=guest
     - RabbitMQ__Password=guest
    ports:
        - 32774:8080
        - 32775:8081
    networks:
        - proxybackend


  msgamification.api:
    image: ${DOCKER_REGISTRY-}msgamificationapi
    container_name: msgamification.api
    build:
      context: .
      dockerfile: Gym/MSGamification/MSGamification.API/Dockerfile
    ports:
        - 32776:8080
        - 32777:8081
    networks:
        - proxybackend

  api.gateway:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: api.gateway
    build:
      context: .
      dockerfile: API.Gateway/Dockerfile
    ports:
        - 32778:8080
        - 32779:8081
    networks:
        - proxybackend

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - proxybackend

  papercut:
    image: changemakerstudiosus/papercut-smtp:latest
    container_name: papercut
    ports:
        - 8080:80
        - 25:25
    networks:
        - proxybackend

  auth.queue:
    image: rabbitmq:management-alpine
    container_name: Auth.Queue
    hostname: auth-queue
    volumes:
       - ./.containers/queue/data/:/var/lib/rabbitmq
       - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge

